### ISSUE TITLE
multiple segment faults caused by NULL poiner in toml_parse.rl

### ISSUE THREAD

**Issue by hongxuchen** [ajwans/libtoml#18]
Multiple crashes happened inside `toml_parse.rl`, which are caused by NULL pointer dereferences in several places.
As of 03e8a3ab1d4d014e63a2befe8a48e74783a81521 , the failure sites contains:
toml_parse.rl:361, toml_parse.rl:342

See comments below for the details.

**Comment by hongxuchen** [comment]
[rl361-1.txt](https://github.com/ajwans/libtoml/files/1061429/rl361-1.txt)


```
	ASAN:SIGSEGV
=================================================================
==36789==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f8c2b7d5b96 sp 0x7ffe8413adb8 bp 0x7ffe8413b630 T0)
    #0 0x7f8c2b7d5b95 in strlen (/lib/x86_64-linux-gnu/libc.so.6+0x8ab95)
    #1 0x7f8c2c1e287f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x3487f)
    #2 0x7f8c2bb1db8c in toml_parse /mnt/188/fix-libtoml/toml_parse.rl:361
    #3 0x401a43 in main /mnt/188/fix-libtoml/main.c:120
    #4 0x7f8c2b76b82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #5 0x401078 in _start (/mnt/188/fix-libtoml/main+0x401078)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 strlen
==36789==ABORTING
```

**Comment by hongxuchen** [comment]
[rl342-1.txt](https://github.com/ajwans/libtoml/files/1061439/rl342-1.txt)

[rl342-2.txt](https://github.com/ajwans/libtoml/files/1061442/rl342-2.txt)


```
	ASAN:SIGSEGV
=================================================================
==36796==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f16b5ab3794 sp 0x7ffe368b2e50 bp 0x7ffe368b2ea0 T0)
    #0 0x7f16b5ab3793 in __interceptor_strcmp (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x37793)
    #1 0x7f16b53ebab4 in toml_parse /mnt/188/fix-libtoml/toml_parse.rl:342
    #2 0x401a43 in main /mnt/188/fix-libtoml/main.c:120
    #3 0x7f16b503982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #4 0x401078 in _start (/mnt/188/fix-libtoml/main+0x401078)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 __interceptor_strcmp
==36796==ABORTING

```
