### ISSUE TITLE
multiple stackoverflow errors caused by toml_parse.rl

### ISSUE THREAD

**Issue by hongxuchen** [ajwans/libtoml#21]
As of 03e8a3ab1d4d014e63a2befe8a48e74783a81521, there are several inputs that cause stackoverflow error, which occur in at least 2 places in `toml_parse.rl`: line 544 and line 627. See comments below for details.

**Comment by hongxuchen** [comment]
[rl544.txt](https://github.com/ajwans/libtoml/files/1061541/rl544.txt)

```
	=================================================================
==36803==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fff3ad44620 at pc 0x7f2957afac81 bp 0x7fff3ad42cf0 sp 0x7fff3ad42ce0
WRITE of size 1 at 0x7fff3ad44620 thread T0
    #0 0x7f2957afac80 in toml_parse /mnt/188/fix-libtoml/toml_parse.rl:544
    #1 0x401a43 in main /mnt/188/fix-libtoml/main.c:120
    #2 0x7f295774782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #3 0x401078 in _start (/mnt/188/fix-libtoml/main+0x401078)

Address 0x7fff3ad44620 is located in stack of thread T0 at offset 5920 in frame
    #0 0x7f2957af7b52 in toml_parse /mnt/188/fix-libtoml/toml_parse.rl:733

  This frame has 13 object(s):
    [32, 36) 'utf16'
    [96, 100) 'malloc_error'
    [160, 164) 'outLen'
    [224, 228) 'err'
    [288, 296) 'parse_error'
    [352, 360) 'new_table_array'
    [416, 432) 'context_stack'
    [480, 512) 'node'
    [544, 600) 'tm'
    [640, 4736) 'stack'
    [4768, 4773) 'utf16_str'
    [4832, 4841) 'utf32_str'
    [4896, 5920) 'string' <== Memory access at offset 5920 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /mnt/188/fix-libtoml/toml_parse.rl:544 toml_parse
Shadow bytes around the buggy address:
  0x1000675a0870: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000675a0880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000675a0890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000675a08a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000675a08b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1000675a08c0: 00 00 00 00[f3]f3 f3 f3 f3 f3 f3 f3 00 00 00 00
  0x1000675a08d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000675a08e0: f1 f1 f1 f1 00 f4 f4 f4 f2 f2 f2 f2 00 00 00 00
  0x1000675a08f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f4 f4
  0x1000675a0900: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000675a0910: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==36803==ABORTING
```

**Comment by hongxuchen** [comment]
[rl627.txt](https://github.com/ajwans/libtoml/files/1061543/rl627.txt)

```
	=================================================================
==36824==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffd211be9f0 at pc 0x7f48f6ee05fe bp 0x7ffd211bd0c0 sp 0x7ffd211bd0b0
WRITE of size 1 at 0x7ffd211be9f0 thread T0
    #0 0x7f48f6ee05fd in toml_parse /mnt/188/fix-libtoml/toml_parse.rl:627
    #1 0x401a43 in main /mnt/188/fix-libtoml/main.c:120
    #2 0x7f48f6b2c82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #3 0x401078 in _start (/mnt/188/fix-libtoml/main+0x401078)

Address 0x7ffd211be9f0 is located in stack of thread T0 at offset 5920 in frame
    #0 0x7f48f6edcb52 in toml_parse /mnt/188/fix-libtoml/toml_parse.rl:733

  This frame has 13 object(s):
    [32, 36) 'utf16'
    [96, 100) 'malloc_error'
    [160, 164) 'outLen'
    [224, 228) 'err'
    [288, 296) 'parse_error'
    [352, 360) 'new_table_array'
    [416, 432) 'context_stack'
    [480, 512) 'node'
    [544, 600) 'tm'
    [640, 4736) 'stack'
    [4768, 4773) 'utf16_str'
    [4832, 4841) 'utf32_str'
    [4896, 5920) 'string' <== Memory access at offset 5920 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /mnt/188/fix-libtoml/toml_parse.rl:627 toml_parse
Shadow bytes around the buggy address:
  0x10002422fce0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002422fcf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002422fd00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002422fd10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002422fd20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10002422fd30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00[f3]f3
  0x10002422fd40: f3 f3 f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00
  0x10002422fd50: 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 f4
  0x10002422fd60: f4 f4 f2 f2 f2 f2 00 00 00 00 00 00 00 00 00 00
  0x10002422fd70: 00 00 00 00 00 00 00 00 f4 f4 f3 f3 f3 f3 00 00
  0x10002422fd80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==36824==ABORTING
```
